apiVersion: v1
kind: Service
metadata:
  name: {{ include "rickandmorty-api.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rickandmorty-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "rickandmorty-api.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}